name: Run Bot

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 235
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: node index.js
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
